# Generated by Django 2.1.1 on 2018-09-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
    ]
